name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.163.18.141 << 'EOF'
            cd nodejs-getting-started || git clone https://github.com/Juumahi/nodejs-getting-started.git && cd nodejs-getting-started
            git pull origin main
            npm install
            pm2 restart all || pm2 start index.js
          EOF
